version: 2.1

master_filter: &master_filter
  branches:
    only: master

develop_filter: &develop_filter
  branches:
    only: develop

feature_filter: &feature_filter
  branches:
    ignore:
      - master
      - develop
orbs:
  node: circleci/node@2.0.1
  slack: circleci/slack@3.2.0

executors:
  node:
    docker:
      - image: circleci/ruby:latest-node

commands:
  build:
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle install
      - run: npm install 
  login_to_expo:
    steps:
      - run: npx expo-cli login -u $EXPO_USERNAME -p $EXPO_PASSWORD    
  publish_to_expo:
    steps:
      - login_to_expo
      - run: npx expo-cli publish --non-interactive --max-workers 1 --release-channel $RELEASE_CHANNEL
  deploy_android:
    steps:
      - run: npx expo-cli build:android --release-channel $RELEASE_CHANNEL --no-publish
      - run: curl -o app.apk "$(npx expo-cli url:apk --non-interactive)"
      - run: bundle exec fastlane android $FASTLANE_LANE
      - store_artifacts:
          path: ~/covid-react/app.apk
  deploy_ios:
    steps:
      - run: npx expo-cli build:ios --release-channel $RELEASE_CHANNEL --non-interactive
      - run: curl -o app.ipa "$(expo url:ipa --non-interactive)"
      - run: bundle exec fastlane ios $FASTLANE_LANE
      - store_artifacts:
          path: ~/covid-react/app.ipa
  

jobs:
  build_and_test:
    executor: node
    working_directory: ~/covid-react
    steps:
      - build
      - run: npm test
  deploy:
    executor: node
    working_directory: ~/covid-react
    steps:
      - build
      - publish_to_expo
      - deploy_android
      - deploy_ios

workflows:
  test_all_pushes:
    jobs:
      - build_and_test
      - deploy:
          context: dev
          # requires:
          #   - build_and_test
  # build_and_test:
  #   jobs:
  #     - build_and_test:
  #         filters: *feature_filter
  dev_deployment:
    jobs:
      - build_and_test:
          filters: *develop_filter
      - deploy:
          filters: *develop_filter
          context: dev
          requires:
            - build_and_test

  master_deployment:
    jobs:
      - build_and_test:
          filters: *master_filter