version: 2.1

master_filter: &master_filter
  branches:
    only: master

develop_filter: &develop_filter
  branches:
    only: develop

feature_filter: &feature_filter
  branches:
    ignore:
      - master
      - develop
orbs:
  node: circleci/node@2.0.1
  slack: circleci/slack@3.2.0

executors:
  node:
    docker:
      - image: circleci/node:10.16

commands:
  build:
    steps:
      - checkout
      - run: npm install      

jobs:
  build-and-test:
    executor: node
    working_directory: ~/covid-react
    steps:
      - build
      - run: npm test
  publish_to_expo_dev:
    executor: node
    working_directory: ~/covid-react
    parameters:
      release_channel:
        description: Expo release channel
        type: string
    steps:
      - build
      - run: npx expo-cli login -u $EXPO_USERNAME -p $EXPO_PASSWORD
      - run: npx expo-cli publish --non-interactive --max-workers 1 --release-channel << parameters.release_channel >>

workflows:
  build-and-test:
    jobs:
      - build-and-test:
          filters: *feature_filter
  dev_deployment:
    jobs:
      - build-and-test:
          filters: *develop_filter
      - publish_to_expo_dev:
          filters: *develop_filter
          release_channel: dev
          requires:
            - build-and-test
  master_deployment:
    jobs:
      - build-and-test:
          filters: *master_filter